### ISSUE TITLE
Use varuint encoding for message prefix

### ISSUE THREAD

**Issue by kyranjamie** [Zondax/ledger-stacks#123]
As discussed in https://github.com/Zondax/ledger-stacks/issues/90 and this [previous bug on geth](https://github.com/ethereum/go-ethereum/issues/14794), the message prefix should be encoded using a variable length integer.

I'm learning as I go, but as far as I understand, this is because ascii decimal encoding presents the issue that `...\n12...` is ambiguous. Is it length `1` with value `2`, or `12`. And that using a varuint encoding fixes this.

[Stacks.js implementation using this encoding](https://github.com/blockstack/stacks.js/blob/dd733abd5f26aff26def0c2d900c89eced173be5/packages/encryption/src/messageSignature.ts#L7-L14)

:link: [zboto Link](https://app.clickup.com/t/2u4e7nv)

**Comment by neithanmo** [comment]
our implementation in a sense uses this approach.. 
the parser reads the first digit and checks if it matches the remaining data len, if not, it moves to the next digit, and now reads both as a len, and check if it matches the remaining data len and so on.
but we can adjust to use this new approach, which is faster than read, check, advance and check again..

**Comment by neithanmo** [comment]
so @kyranjamie this means that after the message prefix(that remains the same), we have 4-byte  that tells the message len, right?

**Comment by kyranjamie** [comment]
I believe so, yes 

For the message `Hello world!` we'd expect: `\x17Stacks Signed Message:\n\fHello world!`
