### ISSUE TITLE
Rename & publish npm package under `@zondax/ledger-stacks`

### ISSUE THREAD

**Issue by kyranjamie** [Zondax/ledger-stacks#125]
Re moving away from Blockstack naming

:link: [zboto Link](https://app.clickup.com/t/2u4e7qz)

**Comment by kyranjamie** [comment]
Package hasn't been published yet 

![image](https://user-images.githubusercontent.com/1618764/184640771-e111c07e-95a0-4bf6-ac11-5fecbdbc271b.png)

**Comment by ftheirs** [comment]
Hi @kyranjamie! The npm package was published and every instance of Blockstack was renamed to Stacks. Keep in mind that class name is no longer BlockstackApp (it was changed to StacksApp).
https://www.npmjs.com/package/@zondax/ledger-stacks
