### ISSUE TITLE
Replace buffer usage with Uint8Array

### ISSUE THREAD

**Issue by aulneau** [Zondax/ledger-stacks#127]
The JS library is assuming the existence of Buffer, it would be better to replace instances of `Buffer` with `Uint8Array` so folks would not need to polyfill it in certain contexts.

:link: [zboto Link](https://app.clickup.com/t/2ufqqjw)

**Comment by carlosala** [comment]
In this case, Ledger libraries for transport are expecting to receive instances of `Buffer` and not `Uint8Array`. You can check the signature of the method `send` that we are using to communicate with the Ledger device [here](https://github.com/LedgerHQ/ledger-live/blob/bf973b09f8a3691acc59131cf63c64ec797bf99b/libs/ledgerjs/packages/hw-transport/src/Transport.ts#L190).
I agree that we should use ES standards!

Thanks for your contribution!
