### ISSUE TITLE
Ledger Nano S screen showing incorrect address (40 instead of 41 characters)

### ISSUE THREAD

**Issue by 314159265359879** [Zondax/ledger-stacks#142]
A user contacted me earlier and I understood the problem as a difference in the address displayed between the wallet on the desktop and on the screen of the Ledger. We used the explorer.stacks.co view of the address to determine the correct address. 

In this image a Ledger Nano S Plus is used and the issue is not reproduced. It is added to illustrate the issue: (A) Desktop address is shown alright, (B) is not but only on a Ledger Nano S. (C) instead of the last digit the 34th digit seemed to be missing for the user using a "Nano Ledger S". 
![image](https://user-images.githubusercontent.com/33360391/210829651-299c294c-bb49-488b-9c91-cb188b6bb3d2.png)

The user has a "Nano Ledger S" device on which the address is split over two screens
Screen 1 shows: SPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (33 characters, missing 5 at the end)
Screen 2 shows: 1234567 (7 characters)

A total of 40 characters shown

Address shown on the Desktop wallet: 
SPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX**5**1234567

A total of 41 characters shown (the correct address as also shown in the explorer for the user)

For clarification only the ledger device is showing an incorrect address omitting the 5 in this example (or 34th character)

I do not have the same device to check if I can reproduce this. It is possible this only occurs when a 41 character address is used, if you want to try and reproduce this yourself. 

Desktop Wallet version used 4.6.1
Stacks Ledger Live app version: 0.23.3

Issue on Stacks repo: https://github.com/hirosystems/stacks-wallet/issues/1147

:link: [zboto Link](https://app.clickup.com/t/86772bp3w)

**Comment by neithanmo** [comment]
Thanks for this detailed report, I will take a look and try to reproduce this.

**Comment by 314159265359879** [comment]
The user experiencing this issue says it is not yet resolved. Is this merged and closed but coming with the next firmware upgrade, not yet live?

**Comment by neithanmo** [comment]
Hi, it was fixed in #146 which includes an update in a module we use to handle UI.
This needs to be reviewed before a new version is published in ledger live, once done users can update the app on the device.

**Comment by neithanmo** [comment]
closed via #146 
changes would be included in the next ledger review.
