### ISSUE TITLE
Support for stacks contract deploys

### ISSUE THREAD

**Issue by edgarkhanzadian** [Zondax/ledger-stacks#153]
Hello!

We are running into an [issue](https://github.com/leather-wallet/extension/issues/4683) with contract deploys using ledger device and I'm wondering if this library supports that feature. If it doesn't, are there any plans to support it in the future?

```json
{
    "signatureRequest": {
      "returnCode": 27012,
      "errorMessage": "Data is invalid : Unsupported transaction payload"
    }
}
```

I've reproduced the bug using tests_zemu on my fork: https://github.com/edgarkhanzadian/ledger-stacks/commit/28923bbc8bb5154d1b1f66a59a627f602ec9796b

:link: [zboto Link](https://app.clickup.com/t/8693f9gbk)

**Comment by neithanmo** [comment]
thanks @edgarkhanzadian i will take a look early next week

**Comment by neithanmo** [comment]
Currently the app only supports the following payloads:
- TokenTransfer
- SmartContract
- ContractCall

**Comment by neithanmo** [comment]
I could not find the documentation for this payload, and [here](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-payloads-1) it is not listed

**Comment by edgarkhanzadian** [comment]
@neithanmo thank you for your time! 

I am trying to sign a transaction that is created by [`makeUnsignedContractDeploy`](https://github.com/hirosystems/stacks.js/blob/main/packages/transactions/src/builders.ts#L903-L988) function. Now, looking at the source code it seems like it is utilizing a function called [`createSmartContractPayload`](https://github.com/hirosystems/stacks.js/blob/main/packages/transactions/src/payload.ts#L132-L159), that creates a payload with id 0x06 if it has clarityVersion supplied to it (which makeUnsignedContractDeploy supplies to it unless it's told not to). 0x06 id was added later on, in sip15, and it specifies that that smart contract should be using version 2 of clarity instead of version 1. https://github.com/stacksgov/sips/blob/main/sips/sip-015/sip-015-network-upgrade.md#new-transaction-versioned-smart-contract

**Comment by neithanmo** [comment]
via #155
