### ISSUE TITLE
Update possibly outdated README

### ISSUE THREAD

**Issue by edgarkhanzadian** [Zondax/ledger-stacks#154]
Hello!

It seems that the library is still stating in README that people should not be using it in production:

> **Do not use in production**

If it is outdated, can we remove this part from the README?

If not, what can be done and how can we help to make it ready for production?

:link: [zboto Link](https://app.clickup.com/t/8693g65cc)

**Comment by neithanmo** [comment]
Hi @edgarkhanzadian 
changes in main branch are not audited, that is why we show that message.
only changes released through ledger live are audited and safe to use.
