### ISSUE TITLE
Stacks Transactions being rejected - Arkadiko, ALEX + Gamma

### ISSUE THREAD

**Issue by pete-watters** [Zondax/ledger-stacks#159]
We are having some issues signing certain transactions in Leather Wallet. https://github.com/leather-io/extension/issues/5115 . It seems like this is an issue with the `ledger-stacks` app as it is also causing problems when we try with Xverse. 

Is this an issue that has been fixed and will be released soon? https://github.com/Zondax/ledger-stacks/issues/157 ?

The problem is happening on Ledger nano S plus (firmware v1.1.1), And Ledger Nano X, with the latest firmware 

The message we get back is:
```
{returnCode: 27012, errorMessage: 'Data is invalid : Unexpected data type’}
```

The problem can be produced using Arkadiko finance:

- Go to `app.arkadiko.finance`
- Sign in with Leather extension and Ledger device connected
- Go to Borrow
- Click any of the three options, for example xBTC, click the borrow button.
- Input amount of xBTC to collateralize
- mint a minimum of 500 USDA
- Click continue
- Click open vault
- Leather popup appears, click confirm
-  We get `{returnCode: 27012, errorMessage: 'Data is invalid : Unexpected data type’}`

Users are also having this same issue when visiting Gamma Stacks NFT marketplace and trying to use Ledger. The Bitcoin ledger app is working but the Stacks app has this same error. 

:link: [zboto Link](https://app.clickup.com/t/8694z0g4j)

**Comment by neithanmo** [comment]
Thanks, @pete-watters  there are many changes in #158 and #156 might solve those issues. it is possible to test them in a real device using the app/pkg/nanos@xx.sh installers

**Comment by neithanmo** [comment]
> The problem is happening on Ledger nano S plus (firmware v1.1.1), And Ledger Nano X, with the latest firmware

Do you know if ledger Nanos also failed? Would it be possible to share the data being sent to the device? it would facilitate finding the issue

**Comment by pete-watters** [comment]
@neithanmo I tested just now and it is also failing using a Nano S. The easiest way to replicate it is to try and generate a signature on Stacking DAO. 

1. Go to https://app.stackingdao.com/signer?pool=SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-pool-v1
2. Authenticate with Leather Wallet
3. Click on either of the "Save Commit Signature" buttons and sign the message

The payload we are sending is:

![Screenshot 2024-07-02 at 17 17 09](https://github.com/Zondax/ledger-stacks/assets/2938440/a8ba164f-1800-48eb-ab22-c9c1eeec03a4)

**Comment by neithanmo** [comment]
This issue would not be fixed by any of the latest changes that will soon be merged.
it is likely that the number of nested values in that structured message is triggering a recursion limit in the app, to avoid consuming the stack that is very limited on nanos/s2/x or an unexpected data type in the message domain or while traversing the msg values.
there is no way to get the serialized data being send to the ledger?  I can not tell with certainty that this is the case. i will take a look at the link and see if I can extract some data to use also in our testing suite

**Comment by neithanmo** [comment]
i do not see any save signature button

![image](https://github.com/Zondax/ledger-stacks/assets/7524579/7f0f5ec9-2b2a-4391-8580-f9f677efb706)

**Comment by pete-watters** [comment]
> i do not see any save signature button
> 
> ![image](https://private-user-images.githubusercontent.com/7524579/345225077-7f0f5ec9-2b2a-4391-8580-f9f677efb706.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODY0MTgsIm5iZiI6MTcxOTk4NjExOCwicGF0aCI6Ii83NTI0NTc5LzM0NTIyNTA3Ny03ZjBmNWVjOS0yYjJhLTQzOTEtODU4MC1mOWY2NzdlZmI3MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDU1NTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWI5Y2M5ZmFkOGUxY2Q4NjAyYjcwNzRkNDc1NjY5MWQ4ZGZjNDgwNDJmNWI2MzkyMWU4ZjVkOGQyYzVhZDkwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HZJr17Fhp7A9HowsiAtVsVEL9EtpOtAsjFASIRDACqQ)

Thanks @neithanmo . 

This issue isn't actually a problem in Leather Wallet itself. It occurs when trying to authorise transactions via Leather. 

So if you sign in with Leather and then follow the steps above:

- Go to https://app.stackingdao.com/signer?pool=SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-pool-v1
- Authenticate with Leather Wallet
- Click on either of the "Save Commit Signature" buttons and sign the message

On Stacking Dao you should see a screen like this where you can replicate the error: 

![Screenshot 2024-07-03 at 06 57 15](https://github.com/Zondax/ledger-stacks/assets/2938440/2f7311e3-5a3f-4a5f-adcf-b2782bfa0ffb)

In the meantime I will try and get the serialised data in case it helps. Thanks!

**Comment by neithanmo** [comment]
Thanks @pete-watters. Is there any update on the **structured_message** being sent to the ledger?
maybe the serialized data? this would help a lot. but looking at the JSON payload you shared, the app checks the domain, and errors, if there are more than 3 fields(name, version, and chain_id), represented as a clarity tuple but it does not verify their values, later it recursively reads the rest of the message checking only that the clarity values are correct:

```rust
    pub fn verify(input: &'a [u8]) -> Result<(), ParserError> {
        let rem = Self::parse_prefix(input)?;
        // parse domain
        let (msg, _) = Domain::from_bytes(rem)?;

        // validate msg, but here we can limit the complexity
        // of the msg we can parse as the device has limited resources.
        //let's evaluate if a recursion limit of MAX_DEPTH is good for
        // general purposed structured data
        Self::validate(msg)?;

        Ok(())
    }
```
we have a recursion limit of MAX_DEPTH, used in case of nested values in the message

**Comment by neithanmo** [comment]
> Hi @neithanmo,
> 
> Apologies for the delay, here is some sample data we are passing to `app.sign_structured_msg`
> 
>     * `stx_derivation_path`: `m/44'/5757'/0'/0/0 `
> 
>     * `domain`: `0c0000000308636861696e2d69640100000000000000000000000000000001046e616d650d0000000c706f782d342d7369676e65720776657273696f6e0d00000005312e302e30`
> 
>     * `payload`: `0c0000000607617574682d696401000000000000000000000000000ca5640a6d61782d616d6f756e7401000000000000003635c9acdd09faf00006706572696f64010000000000000000000000000000000108706f782d616464720c000000020968617368627974657302000000142fffa9a09bb7fa7dced44834d77ee81c49c5f0cc0776657273696f6e0200000001040c7265776172642d6379636c65010000000000000000000000000000005905746f7069630d0000000a6167672d636f6d6d6974 `
> 
> 
> Hopefully that helps? If not let me know and I can try and gather more information

Thank You @pete-watters, That data is what we need. I will put it in our tests suite internally for easy debugging of this bug, hopefully, it would be about adjusting some types/value limits and not due to device limitations. I will keep you posted

**Comment by pete-watters** [comment]
Wow that's great news and thanks for the quick response. I will be slow to reply next week but if you need more assistance contact the team on here https://github.com/leather-io/extension/issues/5115. Thanks again!

**Comment by neithanmo** [comment]
@pete-watters 
after a quick test using the data you provided, I found no issues with it, the app handles it correctly. I was even running inside our device emulator with no errors.
That being said, is this the data causing the "Invalid Data" error?
Bellow the device UI showing part of the message domain and the payload/msg hash:

![00001](https://github.com/Zondax/ledger-stacks/assets/7524579/ae0a1638-e9d5-4144-b635-d0ad5d7f5d2d)

![00002](https://github.com/Zondax/ledger-stacks/assets/7524579/4084b32c-a694-413b-9e25-4a2f04d2e1fa)

![00003](https://github.com/Zondax/ledger-stacks/assets/7524579/e8a496b3-4c97-4e6c-b7e9-804f99e4d34f)

![00004](https://github.com/Zondax/ledger-stacks/assets/7524579/29c7c086-a459-4b90-9ff5-211f40f29467)

![00005](https://github.com/Zondax/ledger-stacks/assets/7524579/796dffb3-9d16-4fac-9b08-d3c910d9dc5f)

**Comment by pete-watters** [comment]
Hey @neithanmo , 

Thanks again for the help here, I am still investigating on our side. Its good if the data passes your emulator however on our side with an actual connected device no action is triggered so I don't see anything on the physical device. 

We just receive the invalid payload error back.

**Comment by 314159265359879** [comment]
@neithanmo we already tested this with nano S+, with firmware 1.1.1 and more recently with 1.1.2. I tested with Windows machine. I am not sure about Pete's OS.

**Comment by pete-watters** [comment]
@neithanmo I am testing it on Mac OS

**Comment by neithanmo** [comment]
I will close for now, provided data did not trigger any error in our integration test or our unit testing.

feel free to open again and provide more detail
