### ISSUE TITLE
Connection to ledger does not work

### ISSUE THREAD

**Issue by Eranity** [Zondax/ledger-stacks#169]
![2024-09-04 14 06 22](https://github.com/user-attachments/assets/031f74aa-8263-40c1-a59d-55a1e4e041d5)

:link: [zboto Link](https://app.clickup.com/t/8695mtq3d)

**Comment by Eranity** [comment]
Connection to ledger live works correctly, but it doesn't work on our platform
Stacks version on Ledger: v0.23.3

**Comment by sourajyoti-gupta** [comment]
Hi @Eranity , please follow this thread (https://github.com/Zondax/ledger-stacks/issues/171), we've released a new [version](https://hub.zondax.ch/stacks) which is currently in testing. I'd request you to uninstall the app, and install the one available on Ledger Live 0.24.2. That should work. Once we roll-up the latest update you should be able to upgrade your app. Thanks!

**Comment by Eranity** [comment]
> Stacks 0.24.5 have been release last week on Ledger Live, can we please close this issue? @Eranity

Hello, thanks for the answer. Yes, we can close this usse.
