### ISSUE TITLE
Cant call big functions with 20+ arguments with stacks ledger app

### ISSUE THREAD

**Issue by VelarBTC** [Zondax/ledger-stacks#175]
Reproduction steps (checked with both released version 0.23.3 and unreleased later version 0.24.5)
Method 1. Visit the dapp https://app.velar.com/swap , call swap function with any combination of tokens .
Method 2. Directly call function 'apply' for contract @ https://explorer.hiro.so/txid/SP1Y5YSTAHZ88XYK1VPDH24GY0HPX5J4JECTMY4A1.path-apply_v1_2_0?chain=mainnet
function args that can be used to call - 
[{"type":11,"list":[{"type":12,"data":{"a":{"type":13,"data":"u"},"b":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"velar-stx","lengthPrefixBytes":1,"maxLengthBytes":128}},"c":{"type":1,"value":"21n"},"d":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"wstx","lengthPrefixBytes":1,"maxLengthBytes":128}},"e":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"velar-token","lengthPrefixBytes":1,"maxLengthBytes":128}},"f":{"type":4}}}]},{"type":1,"value":"2000000n"},{"type":10,"value":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"wstx","lengthPrefixBytes":1,"maxLengthBytes":128}}},{"type":10,"value":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"velar-token","lengthPrefixBytes":1,"maxLengthBytes":128}}},{"type":9},{"type":9},{"type":9},{"type":10,"value":{"type":6,"address":{"type":0,"version":22,"hash160":"7c5f674a8fd08efa61dd9b11121e046dd2c89273"},"contractName":{"type":2,"content":"univ2-share-fee-to","lengthPrefixBytes":1,"maxLengthBytes":128}}},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9},{"type":9}]

This is the current response when using ledger with leather wallet to call above mentioned fucntion 

<img width="1172" alt="Screenshot 2024-10-31 at 8 17 29 PM" src="https://github.com/user-attachments/assets/d135240d-0b30-4436-886d-b3a79fb61709">

**Comment by 314159265359879** [comment]
I see this fails with Leather and Xverse, on Xverse the error is slightly different:
![image](https://github.com/user-attachments/assets/dd85c303-e1eb-44f8-8a70-702e6787d171)

**Comment by 314159265359879** [comment]
Example of a logged serielized transaction before it is send to the Ledger device

generated with [this build](https://github.com/leather-io/extension/actions/runs/11161118067) of Leather: 
`0000000001040097432af9a5c04675136b8c2badfbfe9bf17fa804000000000000003500000000000003e800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003020000000300021697432af9a5c04675136b8c2badfbfe9bf17fa8040100000000000000640003167c5f674a8fd08efa61dd9b11121e046dd2c892730a756e6976322d636f72650500000000000000010103167c5f674a8fd08efa61dd9b11121e046dd2c892730a756e6976322d636f7265167c5f674a8fd08efa61dd9b11121e046dd2c892730b76656c61722d746f6b656e0576656c6172030000000000000b3f02167c5f674a8fd08efa61dd9b11121e046dd2c8927311706174682d6170706c795f76315f325f30056170706c79000000180b000000010c0000000601610d0000000175016206167c5f674a8fd08efa61dd9b11121e046dd2c892730976656c61722d73747801630100000000000000000000000000000015016406167c5f674a8fd08efa61dd9b11121e046dd2c892730477737478016506167c5f674a8fd08efa61dd9b11121e046dd2c892730b76656c61722d746f6b656e01660401000000000000000000000000000000640a06167c5f674a8fd08efa61dd9b11121e046dd2c8927304777374780a06167c5f674a8fd08efa61dd9b11121e046dd2c892730b76656c61722d746f6b656e0909090a06167c5f674a8fd08efa61dd9b11121e046dd2c8927312756e6976322d73686172652d6665652d746f09090909090909090909090909090909`

**Comment by neithanmo** [comment]
This error occurs due to a limitation on the number of contract call arguments we support in normal mode, which is capped at 10. To sign a transaction with more than 10 arguments, please enable Expert Mode in your Ledger app.

In a future release, we may consider increasing this limit to 20 or removing the restriction entirely if needed.

I will close for now, feel free to open again if even in expert mode it fails
